### ISSUE TITLE
Wrapping concept

### ISSUE THREAD

**Issue by vol-lev** [joseftw/EPiServer-ContentData-ToJson#19]
Hi Josef, 
could you please describe the concept of wrapping/not-wrapping items in the content area? I'm upgrading from the Jos.ContentJson, the app is based on react and I can't refactor FE code at the moment. I see in some places content area items rendered unwrapped (which is the natural representation of the content area), and in some places items are wrapped (grouped by content type). 
However in the new ContentSerialzier it seems like it's driven by a global setting (IContentSerializerSettings is injected into the property handler, though JsonContentSerializer.GetStructuredData just creates new ContentSerializerSettings()). So it would be great if you can describe the designed usage of this feature!

**Comment by vol-lev** [comment]
just a thought - from my current understanding the easiest is to wrap Handling parameters into a HandlingContext class and make serializer settings a part of this context (and it would be a very breaking change :) ). 

`    public interface IHandlingContext
    {
        PropertyInfo Property { get; }
        IContentData ContentData { get; }
        IContentSerializerSettings SerializerSettings { get; }
    }

    public interface IPropertyHandler<in T>
    {
        object Handle(IHandlingContext context, T value);
    }`

what do you think about it (the concept question is more important :) )?

**Comment by joseftw** [comment]
You can use the ```ContentSerializerWrapItemsAttribute```

https://github.com/joseftw/JOS.ContentSerializer/blob/develop/src/JOS.ContentSerializer/Attributes/ContentSerializerWrapItemsAttribute.cs

It's used by the ```ContentAreaPropertyHandler```

https://github.com/joseftw/JOS.ContentSerializer/blob/develop/src/JOS.ContentSerializer/Internal/Default/ContentAreaPropertyHandler.cs#L91
