### ISSUE TITLE
Using .ToJson() with IContentEvents

### ISSUE THREAD

**Issue by kmukku** [joseftw/EPiServer-ContentData-ToJson#20]
I'm trying to set up listener to publish event, which would publish the page to another endpoint. Is this possible? Currently I'm not getting the right results.

        public void EventsPublishedContent(object sender, ContentEventArgs e)
        {
                var page = (e.Content as ContentData);
                var pageAsJson = page.ToJson(); // results in either empty or suppressed set of properties.

**Comment by joseftw** [comment]
You need to give me more information. Could you share a [MCVE](https://stackoverflow.com/help/mcve)?

"Suppressed set of properties", what do you mean?
What does your ContentType look like?
Are you using the DisplayAttributes on your properties? The default property resolver works like this: https://github.com/joseftw/JOS.ContentSerializer#ipropertyresolver

**Comment by kmukku** [comment]
It was the property resolver. I didn't have any attributes on my properties, but base page was having properties with attributes so only those did show up. Thanks for pointing into right direction!
