### ISSUE TITLE
UrlPropertyHandler does not work correctly for some cases

### ISSUE THREAD

**Issue by mickiewicz** [joseftw/EPiServer-ContentData-ToJson#24]
I think `UrlPropertyHandler` currently doesn't work as it should. Now it checks if a url is absolute, I think it should checks if the link is external instead. For internal it should call:
`this._urlHelper.ContentUrl(url, contentSerializerSettings.UrlSettings)`
Please check two failing tests.

**Comment by joseftw** [comment]
Could you provide more information? Maybe add a PR with a failing test? All tests are green for me.
