### ISSUE TITLE
How to serialize enums ?

### ISSUE THREAD

**Issue by MichalGrzegorzak** [joseftw/EPiServer-ContentData-ToJson#27]
Currently Serializer skips all enums, any clues how to handle them?

**Comment by joseftw** [comment]
Hello!

I will try to have a look this weekend if I have some time, shouldn't be that big of a deal to add support for enum.

**Comment by joseftw** [comment]
Something like this should work out of the box:
My enum is named ```MyEnum``` in the example below.

**MyEnum**

    public enum MyEnum
    {
        Undefined = 0,
        FirstValue = 1,
        SecondValue = 2,
        ThirdValue = 3
    }

Create a propertyhandler for the specific enum like this:

**MyEnumPropertyHandler**

    public class MyEnumPropertyHandler : IPropertyHandler<MyEnum>
    {
        public object Handle(MyEnum value, PropertyInfo property, IContentData contentData)
        {
            var enumType = value.GetType();
            var enumValues = Enum.GetValues(enumType);
            var values = new List<EnumProperty>();

            foreach (var enumValue in enumValues)
            {
                var enumName = Enum.GetName(enumType, enumValue);
                var enumProperty = new EnumProperty
                {
                    Name = enumName,
                    Value = (int)enumValue,
                    Selected = value.Equals(enumValue)
                };
                values.Add(enumProperty);
            }

            return values;
        }
    }

**EnumProperty**

    public class EnumProperty
    {
        public int Value { get; set; }
        public string Name { get; set; }
        public bool Selected { get; set; }
    }

Then register the propertyhandler in a initalizationmodule

    public class CustomPropertyHandlerInitializationModule
    {
        [InitializableModule]
        [ModuleDependency(typeof(EPiServer.Web.InitializationModule))]
        public class ContentSerializerInitalizationModule : IConfigurableModule
        {
            public void Uninitialize(InitializationEngine context)
            {

            }

            public void ConfigureContainer(ServiceConfigurationContext context)
            {
                context.Services.AddSingleton<IPropertyHandler<MyEnum>, MyEnumPropertyHandler>();
            }

            public void Initialize(InitializationEngine context)
            {

            }
        }
    }

This produces the following json for me:

    {
	....
	"myEnum": [{
		"value": 0,
		"name": "Undefined",
		"selected": true
	}, {
		"value": 1,
		"name": "FirstValue",
		"selected": false
	}, {
		"value": 2,
		"name": "SecondValue",
		"selected": false
	}, {
		"value": 3,
		"name": "ThirdValue",
		"selected": false
	}],
    .........
