### ISSUE TITLE
Add IContractResolver to ContentSerializerSettings

### ISSUE THREAD

**Issue by dinakarcodejumper** [joseftw/EPiServer-ContentData-ToJson#28]
I am trying to output json in snake_case

`{"blocks": [{ "block_name" : { "property_name1" : "value", "property_name2": "value2"}}]}`

However I am getting this in my output:

`{"blocks": [{ "blockName" : { "propertyName1" : "value", "propertyName2": "value2"}}]}`

After applying the ContentSerializerNameAttribute I got the output JSON one step closer. 

`{"blocks": [{ "blockName" : { "property_name1" : "value", "property_name2": "value2"}}]}`

It seems the ContentSerializer is defaulting to Camel Case.  Even if I can get it to work its still time consuming to apply the attribute across all blocks. 
I noticed that the JSONContentSerializer sets the default to camel case? I was wondering if we could  modify the logic to use ContentSerializerSettings to apply casing on the output JSON?

**Comment by joseftw** [comment]
Hello!

I think you can solve this by implementing your own IPropertyNameStrategy.

You can have a look here, this is the default one. Just create your own implementation and you should be good to go :)

https://github.com/joseftw/JOS.ContentSerializer/blob/develop/src/JOS.ContentSerializer/Internal/PropertyNameStrategy.cs


Another option is to implement your own IContentJsonSerializer, that would give you even more control. More info in the readme.

**Comment by dinakarcodejumper** [comment]
Thank you. Custom implementation of IContentJsonSerializer worked for me.
