### ISSUE TITLE
Add ID to Serializer

### ISSUE THREAD

**Issue by dinakarcodejumper** [joseftw/EPiServer-ContentData-ToJson#29]
I am trying to output JSON as follows: 
` {
    "block_name": {
      "id": 2347,
      "heading": "Primary Heading",
      "subHeading": "Sub Heading",
      "subTitle": "Sub Title",
      "summary": "Summary content"
      }}
      `
Is there a way to add the Block ID to output JSON ?

**Comment by joseftw** [comment]
I think you can add the id in the same way as I add the type in this issue.

https://github.com/joseftw/JOS.ContentSerializer/issues/6
