### ISSUE TITLE
XHtmlString no longer supported?

### ISSUE THREAD

**Issue by MichalGrzegorzak** [joseftw/EPiServer-ContentData-ToJson#4]
Hi, 
did You drop support for XHtmlString? 
All properties of that type, are null in Json.  I can`t find a Helper for this type in the code, any clue?

**Comment by joseftw** [comment]
Looks like I accidentally removed it...will add it again ASAP

**Comment by joseftw** [comment]
I've now updated the code and pushed version 2.9.961 to Nuget.
