### ISSUE TITLE
Set object type as object property on ContentAreaItem

### ISSUE THREAD

**Issue by heinzmuller** [joseftw/EPiServer-ContentData-ToJson#6]
The functionality to add the content type as a property on each ContentAreaItem would be very useful when using `wrapItems: false` as I believe when `wrapItems` is true you loose the order in the ContentArea if there are multiple types of content

In our example we have a VideoListBlock which can contain both VimeoVideoBlocks and YoutubeVideoBlocks and a json structure like below would make this package a lot more useful for us.

```
{
    "videos": [
        {
            "__contentType": "YoutubeVideoBlock",
            "videoId": "abc123",
            "youtubeSpecificProperty": true,
            "image": "image1.jpg"
        },
        {
            "__contentType": "VimeoVideoBlock",
            "videoId": "abc123",
            "vimeoSpecificProperty": false,
            "image": "image2.jpg"
        },
        {
            "__contentType": "YoutubeVideoBlock",
            "videoId": "abc123",
            "youtubeSpecificProperty": false,
            "image": "image3.jpg"
        }
    ]
}
```

**Comment by joseftw** [comment]
Hello
If you add the following property to your Youtube/VimeoVideoBlock it should work right away:

`
public string ContentType => nameof(YoutubeVideoBlock);
`

I've tested it very quickly and I got the following JSON:
**currentPage.ToJson();**

    {
        "mainContentArea": {
            "youtubeVideoBlock": [{
                "name": "I am Youtube 1",
                "contentType": "YoutubeVideoBlock"
            }, {
                "name": "I am Youtube 2",
                "contentType": "YoutubeVideoBlock"
            }],
            "vimeoVideoBlock": [{
                "name": "I am Vimeo 1",
                "contentType": "VimeoVideoBlock"
            }, {
                "name": "I am Vimeo 2",
                "contentType": "VimeoVideoBlock"
            }]
        }
    }

**currentPage.MainContentArea.ToJson(false)**

    [{
        "name": "I am Youtube 1",
        "contentType": "YoutubeVideoBlock"
    }, {
        "name": "I am Vimeo 1",
        "contentType": "VimeoVideoBlock"
    }, {
        "name": "I am Vimeo 2",
        "contentType": "VimeoVideoBlock"
    }, {
        "name": "I am Youtube 2",
        "contentType": "YoutubeVideoBlock"
    }]

**Comment by heinzmuller** [comment]
That is indeed a more elegant solution!
